version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - forbidigo

  settings:
    forbidigo:
      forbid:
        - pattern: "^panic$"
          msg: "Do not use panic(). Return an error instead."
